language: node_js
sudo: false
node_js:
  - "stable"
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE more-recipes-test;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'diligence';" -U postgres
install: 
  - npm install
script:
  - npm test
env:
  - NODE_ENV=test
cache:
  directories:
   - "node_modules"
after_success:
  - npm run coverage
branches:
  only:
    - develop
    - ch-tests-and-integration-150888969

notifications:
  webhooks:
    - https://coveralls.io/webhook
  repo_token:
    - pfnX34pRk2afky5CXwDD6jUJ6glW9VL0u
